-- ─────────────────────────────────────────────────────────────
-- 4주차 비교과 · 근거노트 표 (evidence) 와 저장 확인 기록 표 (evidence_check)
-- Supabase 대시보드 → SQL Editor 에 통째로 붙여 넣고 Run.
-- 여러 번 실행해도 같은 결과가 되도록 if not exists / drop policy if exists 를 쓴다.
-- ─────────────────────────────────────────────────────────────

-- 1) 근거노트 한 장 = 한 행.  3주차 카드의 네 칸(값·단위·출처·조회일)에 항목 이름을 더한 다섯 칸.
--    id · created_at 은 Supabase 가 새 표에 붙여 주는 자동 열과 같은 꼴로 둔다.
create table if not exists public.evidence (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  item        text    not null,   -- 항목 이름   예) 천안시 제3종일반주거지역 용적률
  value       numeric not null,   -- 값(숫자만)  예) 300      ← '300% 이하' 를 통째로 넣지 않는다
  unit        text    not null,   -- 단위        예) % 이하   ← 상한/하한 표시는 단위의 일부
  source      text    not null,   -- 출처        예) 천안시 도시계획 조례 제61조제1항제5호 (조례 제2613호, 시행 2024-05-17)
  queried_on  date    not null    -- 조회일      예) 2026-09-21
);

-- 폼의 '빈칸 금지' 는 화면 규칙일 뿐이다. 다른 경로(직접 API 호출)로 들어온 빈 문자열도 서버가 거부하게 한다.
alter table public.evidence drop constraint if exists evidence_text_not_blank;
alter table public.evidence add constraint evidence_text_not_blank
  check (length(btrim(item)) > 0 and length(btrim(unit)) > 0 and length(btrim(source)) > 0);

-- 2) RLS — 켜고, 팀(publishable 키 = anon 역할)이 읽고 추가할 수 있는 정책만 둔다.
--    수정·삭제 정책은 두지 않는다 → 브라우저에서는 행을 고치거나 지울 수 없고, Table Editor(관리자)에서만 가능.
alter table public.evidence enable row level security;

drop policy if exists "팀 읽기" on public.evidence;
create policy "팀 읽기" on public.evidence
  for select to anon, authenticated
  using (true);

drop policy if exists "팀 추가" on public.evidence;
create policy "팀 추가" on public.evidence
  for insert to anon, authenticated
  with check (true);

-- 3) 저장 확인 기록 — 과제 ③ '새로고침·다른 기기·팀원 브라우저에서 같은 행이 보이는지 확인한 기록'.
--    각 브라우저가 '보인다' 를 눌렀을 때 그 순간 서버에서 받은 행 수를 함께 남긴다.
create table if not exists public.evidence_check (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  place       text not null check (place in ('새로고침', '다른 기기', '팀원 브라우저')),
  seen_rows   integer not null check (seen_rows >= 0),
  who         text not null check (length(btrim(who)) > 0),  -- 확인한 사람 / 기기 이름
  agent       text not null                                   -- 브라우저 · OS 요약 (자동)
);

alter table public.evidence_check enable row level security;

drop policy if exists "팀 읽기" on public.evidence_check;
create policy "팀 읽기" on public.evidence_check
  for select to anon, authenticated
  using (true);

drop policy if exists "팀 추가" on public.evidence_check;
create policy "팀 추가" on public.evidence_check
  for insert to anon, authenticated
  with check (true);

-- 4) 테이블 권한 — Data API 가 anon 역할로 이 표에 접근할 수 있게 한다 (RLS 정책은 그 위에서 행을 거른다).
grant select, insert on public.evidence, public.evidence_check to anon, authenticated;
grant usage on all sequences in schema public to anon, authenticated;
